### ISSUE TITLE
question(summon)payload behavior unexpected

### ISSUE THREAD

**Issue by serfend** [SignorMercurio/Heap-Tutorials#1]
seems two summons used differences chunk.
![image](https://user-images.githubusercontent.com/20139227/174693272-52ef5912-96c6-45ea-9be2-402700202dca.png)

**Comment by serfend** [comment]
seems i can successfully run in remote , but in local kali that not valid

**Comment by SignorMercurio** [comment]
> seems i can successfully run in remote , but in local kali that not valid

Yes, it's widely known that Kali has different behaviors in heap-related challenges (and some stack-related challenges too) compared to Ubuntu in multiple libc versions, which is why it's not recommended for Pwn but Pentesting purposes.

**Comment by serfend** [comment]
get!thank a lot for your reply
